### ISSUE TITLE
WeakLensingValidation

### ISSUE THREAD

**Issue by aguinot** [aguinot/WeakLensingValidation#6]
he goal of this package is to provide a set of tools to run tests on weak lensing catalogs. It will be also possible to perform object selection to build a dedicated sample for science use cases. The entire library will be powered by [dask](https://www.dask.org/) which make some computation faster and allow large catalogs without using too much memory.

Current features:
- [x] Configuration with a `.yaml` file #1 
- [x] Read catalogs with `dask` and `vaex` #3 
- [x] Make plot of PSF residuals on the focal plane #5 
- [ ] Make rho_stats plot
- [ ] PSF leakage using the PSF at galaxy positions
- [ ] PSF leakage with correlation function (alpha leakage)
- [ ] Xi_systematic
- [ ] Measure the COSEBIs for any set of scales
- [ ] Pseudo Cl B-modes
- [ ] Mass maps on the sphere (using healpy)
- [x] Compute correlation functions #8
- [ ] Internal cosmology model (powered by CCL)
- [ ] Handle external `n(z)` (potentially multiple ones)
- [ ] Make all sorts of basic plot: `plot`, `hist`, `hexbin`, `scatter`

**Comment by aboucaud** [comment]
General idea : change python package name to something easier to type like `wl-validation`.
Otherwise it's a pain to write and use and differs from the general rules.
